import { LegalDocumentContent } from '../screens/settings/LegalDocumentScreen';

const CONTACT_EMAIL = 'legal@legate.app';
const LAST_UPDATED = 'July 2026';

export const PRIVACY_POLICY: LegalDocumentContent = {
  title: 'Privacy Policy',
  lastUpdated: LAST_UPDATED,
  intro:
    'Legate ("we," "our," "the app") helps you record financial, legal, and personal information in a private vault, and lets you designate trusted people who can request access after your death. This policy explains what information we collect, how it is stored and protected, and who can see it.',
  sections: [
    {
      heading: '1. Information We Collect',
      body:
        'Account information: your name and email address, collected when you sign up with email/password or Google sign-in. If you sign in with Google, we also receive your Google profile photo, which is shown as your avatar in the app.\n\nVault contents: the financial accounts, insurance policies, legal documents, digital assets, contacts, and final wishes you choose to store, organized into categories you select.\n\nTrusted person information: the name, email address, and relationship you provide when inviting someone as a trusted person.\n\nDocuments and certificates: files you upload, such as estate documents or a death certificate submitted as part of the vault-unlock process.\n\nUsage and settings: your subscription plan, and app preferences such as whether biometric lock and notifications are enabled.',
    },
    {
      heading: '2. How Your Vault Data Is Protected',
      body:
        'Sensitive fields in your vault items (such as account numbers and passwords) are encrypted on your device using AES-256 before being sent to our servers, with a unique encryption key generated on your device and stored in your device\'s secure hardware storage (Keychain on iOS, Keystore on Android). This means the encryption key never leaves your device and is not stored on our servers.\n\nBecause the key lives only on your device, if you uninstall the app or reset your device without transferring that key, previously stored vault data cannot be recovered — not even by us.\n\nDocuments and death certificates you upload are stored in private cloud storage and are not publicly accessible; they can only be retrieved through short-lived, authenticated links generated by the app.',
    },
    {
      heading: '3. How We Use Your Information',
      body:
        'We use your information to operate the app\'s core features: storing and displaying your vault, sending invitation emails to trusted people, running the vault-unlock and estate-checklist workflows, enforcing plan limits, and authenticating you.\n\nWe do not sell your personal information or vault contents to third parties, and we do not use your vault contents for advertising.',
    },
    {
      heading: '4. Who Can See Your Information',
      body:
        'By default, only you can view or decrypt your vault contents. Trusted people you invite cannot see your vault until a death-verification request on your account has been confirmed by a second, different trusted person and a waiting period has passed. This "two-key" process is enforced by our backend, not just by the app\'s interface.\n\nOnce your vault unlocks, your accepted trusted people can view your vault items, documents, and estate checklist, and can mark subscriptions as cancelled. They cannot alter any other information in your vault.\n\nWe use third-party service providers to operate the app: Supabase for our database, authentication, and file storage; Resend for sending invitation emails; and Google for Google sign-in. These providers process data on our behalf and are not permitted to use it for their own purposes.',
    },
    {
      heading: '5. Data Retention and Deletion',
      body:
        'We retain your account and vault information for as long as your account is active. If you would like your account and associated data deleted, contact us using the details below.',
    },
    {
      heading: '6. Children\'s Privacy',
      body:
        'Legate is not directed at children, and we do not knowingly collect information from anyone under 16.',
    },
    {
      heading: '7. Changes to This Policy',
      body:
        'We may update this policy as the app changes. Material changes will be reflected in the "Last updated" date above.',
    },
    {
      heading: '8. Contact Us',
      body: `Questions about this policy or your data can be sent to ${CONTACT_EMAIL}.`,
    },
  ],
};

export const TERMS_OF_SERVICE: LegalDocumentContent = {
  title: 'Terms of Service',
  lastUpdated: LAST_UPDATED,
  intro:
    'These terms govern your use of Legate. By creating an account, you agree to these terms.',
  sections: [
    {
      heading: '1. What Legate Does',
      body:
        'Legate lets you ("the vault owner") record financial accounts, insurance, legal documents, digital assets, and final wishes in a private, encrypted vault, and designate trusted people who may request access after your death, subject to a two-person confirmation process and a waiting period.',
    },
    {
      heading: '2. Your Account',
      body:
        'You are responsible for keeping your login credentials secure and for the accuracy of the information you store. You must provide a real, working email address so that trusted-person invitations and account communications reach you.',
    },
    {
      heading: '3. Trusted Persons and the Unlock Process',
      body:
        'You may invite trusted people by name, email, and relationship. An invited person only gains access to your vault after: (a) they accept the invitation by signing up or logging in with the invited email address, and (b) a death-verification request on your vault is submitted by one trusted person, confirmed by a second, different trusted person, and the waiting period configured in the app has fully elapsed.\n\nYou may cancel or reject a death-verification request on your own vault at any time before it unlocks, for example if it was submitted in error.\n\nOnce unlocked, trusted people can view your vault, documents, and estate checklist, and mark subscriptions as cancelled, but cannot make other changes to your vault.',
    },
    {
      heading: '4. Subscription Plans',
      body:
        'Legate offers free and paid plans with different limits on vault items, trusted people, and document uploads, described in the app\'s upgrade screen. At this time, selecting a paid plan in the app updates your account\'s plan for demonstration purposes only — no payment is currently processed. Real billing will be clearly described here once payment processing is enabled.',
    },
    {
      heading: '5. Your Responsibilities',
      body:
        'You agree not to use Legate to store information you do not have the right to store, to impersonate another person when inviting trusted people, or to attempt to interfere with the security of the app or other users\' vaults.',
    },
    {
      heading: '6. Data Loss',
      body:
        'Vault item encryption keys are stored only on your device\'s secure hardware storage. If your device is lost, reset, or the app is uninstalled without that key being preserved, encrypted vault data cannot be recovered by you or by us. You are responsible for maintaining access to a device that holds your encryption key, or for keeping your vault contents up to date across devices where supported.',
    },
    {
      heading: '7. No Legal, Financial, or Estate-Planning Advice',
      body:
        'Legate is an organizational tool. It does not provide legal, financial, tax, or estate-planning advice, and the estate checklist it generates is a general starting point, not professional guidance. You should consult qualified professionals for advice specific to your situation.',
    },
    {
      heading: '8. Service Availability',
      body:
        'We aim to keep Legate available and reliable, but we do not guarantee uninterrupted access. Features described as in-development elsewhere in the app (such as push notifications or an activity log) are not yet available.',
    },
    {
      heading: '9. Termination',
      body:
        'You may stop using Legate and request account deletion at any time. We may suspend or terminate accounts that violate these terms.',
    },
    {
      heading: '10. Changes to These Terms',
      body:
        'We may update these terms as the app evolves. Continued use of the app after changes take effect constitutes acceptance of the updated terms.',
    },
    {
      heading: '11. Contact Us',
      body: `Questions about these terms can be sent to ${CONTACT_EMAIL}.`,
    },
  ],
};
